apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leshy

resources:
- ./site
- geth-deploy.yaml
- geth-svc.yaml
- ethstats-deploy.yaml
- ethstats-svc.yaml
- ethstats-ingress.yaml

configMapGenerator:
- name: geth-config
  behavior: merge
  files:
  - entrypoint.sh
